import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "My Resume",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <head>
        <script src="https://bat.bing.com/p/insights/s/0.8.45"></script>
        <script src="https://bat.bing.com/p/insights/t/26347591"></script>
        <script
          src="https://connect.facebook.net/signals/config/162268047750936?v=2.9.248&amp;r=stable&amp;domain=www.jobleads.com&amp;hme=17590b9a2e1b26755cdc9ecb401f9f46bca979d3ccce95d786db0936167af731&amp;ex_m=94%2C156%2C134%2C20%2C67%2C68%2C127%2C63%2C43%2C128%2C72%2C62%2C10%2C141%2C80%2C15%2C93%2C28%2C122%2C115%2C70%2C73%2C121%2C138%2C102%2C143%2C7%2C3%2C4%2C6%2C5%2C2%2C81%2C91%2C144%2C224%2C167%2C57%2C226%2C227%2C50%2C183%2C27%2C69%2C232%2C231%2C170%2C30%2C56%2C9%2C59%2C87%2C88%2C89%2C95%2C118%2C29%2C26%2C120%2C117%2C116%2C135%2C71%2C137%2C136%2C45%2C55%2C111%2C14%2C140%2C40%2C213%2C215%2C177%2C23%2C24%2C25%2C17%2C18%2C39%2C35%2C37%2C36%2C76%2C82%2C86%2C100%2C126%2C129%2C41%2C101%2C21%2C19%2C107%2C64%2C33%2C131%2C130%2C132%2C123%2C22%2C32%2C54%2C99%2C139%2C65%2C16%2C133%2C104%2C31%2C193%2C163%2C284%2C211%2C154%2C196%2C189%2C164%2C97%2C119%2C75%2C109%2C49%2C44%2C103%2C42%2C108%2C114%2C53%2C60%2C113%2C48%2C51%2C47%2C90%2C142%2C0%2C112%2C13%2C110%2C11%2C1%2C52%2C83%2C58%2C61%2C106%2C79%2C78%2C145%2C146%2C84%2C85%2C8%2C92%2C46%2C124%2C77%2C74%2C66%2C105%2C96%2C38%2C125%2C34%2C98%2C12%2C147"
        ></script>
        <script src="https://connect.facebook.net/en_US/fbevents.js"></script>
        <script src="https://scripts.clarity.ms/0.8.45/clarity.js"></script>
        <script src="https://www.googletagmanager.com/gtm.js?id=GTM-N3JWH8"></script>
        <script data-document-language="true" data-domain-script="094973b2-3748-4a7a-b5b7-d90c7a936ef1"
          src="https://cdn.cookielaw.org/scripttemplates/otSDKStub.js"></script>
        <link rel="modulepreload" as="script" crossOrigin="" href="https://www.jobleads.com/_nucf/_id_.f17776965.js" />
        <link rel="modulepreload" as="script" crossOrigin=""
          href="https://www.jobleads.com/_nucf/arrow-left-alt.es.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin=""
          href="https://www.jobleads.com/_nucf/utils-Cw5TUUnD.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin="" href="https://www.jobleads.com/_nucf/palette.es.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin="" href="https://www.jobleads.com/_nucf/useEditPage.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin="" href="https://www.jobleads.com/_nucf/v3.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin=""
          href="https://www.jobleads.com/_nucf/documentStore.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin=""
          href="https://www.jobleads.com/_nucf/useResumeBuilderApi.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin="" href="https://www.jobleads.com/_nucf/default.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin="" href="https://www.jobleads.com/_nucf/NuxtImg.vue.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin="" href="https://www.jobleads.com/_nucf/nuxt-link.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin="" href="https://www.jobleads.com/_nucf/client-only.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin="" href="https://www.jobleads.com/_nucf/useMobile.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin="" href="https://www.jobleads.com/_nucf/JluIcon.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin="" href="https://www.jobleads.com/_nucf/Uploader.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin="" href="https://www.jobleads.com/_nucf/quizStore.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin=""
          href="https://www.jobleads.com/_nucf/useSmartModal.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin="" href="https://www.jobleads.com/_nucf/jobDetails.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin=""
          href="https://www.jobleads.com/_nucf/useSocialLink.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin=""
          href="https://www.jobleads.com/_nucf/useRouteHelpers.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin="" href="https://www.jobleads.com/_nucf/useSnackbar.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin="" href="https://www.jobleads.com/_nucf/modalStore.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin=""
          href="https://www.jobleads.com/_nucf/breakpointsStore.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin=""
          href="https://www.jobleads.com/_nucf/notificationStore.f1777696.js" />
        <link rel="preload" href="https://cdn.optimizely.com/js/5676741851611136.js" as="script" crossOrigin="anonymous" />
        <script src="https://cdn.optimizely.com/js/5676741851611136.js" crossOrigin="anonymous"></script>
        <link rel="modulepreload" as="script" crossOrigin=""
          href="https://www.jobleads.com/_nucf/AppHeaderAuroraLoggedIn.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin="" href="https://www.jobleads.com/_nucf/entry.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin="" href="https://www.jobleads.com/_nucf/delete.es.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin=""
          href="https://www.jobleads.com/_nucf/keyboard-backspace.es.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin=""
          href="https://www.jobleads.com/_nucf/LoaderSpinner.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin="" href="https://www.jobleads.com/_nucf/upload.es.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin="" href="https://www.jobleads.com/_nucf/diamond.es.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin="" href="https://www.jobleads.com/_nucf/help.es.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin="" href="https://www.jobleads.com/_nucf/settings.es.f1777696.js" />
        <link rel="stylesheet" crossOrigin="" href="https://www.jobleads.com/_nucf/AppHeaderAuroraLoggedIn.f1777696.css" />
        <link rel="modulepreload" as="script" crossOrigin=""
          href="https://www.jobleads.com/_nucf/AppFooterAurora.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin="" href="https://www.jobleads.com/_nucf/svg-C72FKHqQ.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin=""
          href="https://www.jobleads.com/_nucf/_plugin-vue_export-helper-CHgC5LLL.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin="" href="https://www.jobleads.com/_nucf/svg-DN1m67bg.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin="" href="https://www.jobleads.com/_nucf/svg-CnXPQqeY.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin=""
          href="https://www.jobleads.com/_nucf/ResumeBuilderEditorFormPrimary.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin=""
          href="https://www.jobleads.com/_nucf/useEditorTracking.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin="" href="https://www.jobleads.com/_nucf/check.es.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin=""
          href="https://www.jobleads.com/_nucf/drag-indicator.es.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin=""
          href="https://www.jobleads.com/_nucf/keyboard-arrow-up.es.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin=""
          href="https://www.jobleads.com/_nucf/useResumeBuilder.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin="" href="https://www.jobleads.com/_nucf/useSortable.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin=""
          href="https://www.jobleads.com/_nucf/ResumeTemplateWrapper.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin=""
          href="https://www.jobleads.com/_nucf/ResumeTemplateWrapper.vue.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin=""
          href="https://www.jobleads.com/_nucf/AppFooterAuroraDefault.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin=""
          href="https://www.jobleads.com/_nucf/AppFooterAuroraMarketingAdditionalMenu.vue.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin="" href="https://www.jobleads.com/_nucf/svg-BLWuVUR9.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin="" href="https://www.jobleads.com/_nucf/svg-DSdyTg9x.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin="" href="https://www.jobleads.com/_nucf/UIPopover.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin=""
          href="https://www.jobleads.com/_nucf/UIPopover.vue.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin="" href="https://www.jobleads.com/_nucf/svg-QmhzXl2Z.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin="" href="https://www.jobleads.com/_nucf/svg-C1Aa7htn.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin="" href="https://www.jobleads.com/_nucf/svg-CJt3ke-J.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin=""
          href="https://www.jobleads.com/_nucf/ResumeBuilderEditorFormAddSection.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin=""
          href="https://www.jobleads.com/_nucf/add-circle.es.f1777696.js" />
        <link rel="stylesheet" crossOrigin=""
          href="https://www.jobleads.com/_nucf/ResumeBuilderEditorFormAddSection.f1777696.css" />
        <link rel="modulepreload" as="script" crossOrigin=""
          href="https://www.jobleads.com/_nucf/CountrySelector.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin=""
          href="https://www.jobleads.com/_nucf/CountrySelector.vue.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin=""
          href="https://www.jobleads.com/_nucf/svg-QmhzXl2Z-DdWm7Z5c.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin=""
          href="https://www.jobleads.com/_nucf/_plugin-vue_export-helper-CHgC5LLL-BmOybl0N.f17776962.js" />
        <link rel="modulepreload" as="script" crossOrigin=""
          href="https://www.jobleads.com/_nucf/QuizPluginWrapper.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin="" href="https://www.jobleads.com/_nucf/svg-B_WOQ4cf.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin="" href="https://www.jobleads.com/_nucf/svg-DudBsw5b.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin=""
          href="https://www.jobleads.com/_nucf/svg-CoAYAUiO-BkXSKEOQ.f17776962.js" />
        <link rel="modulepreload" as="script" crossOrigin="" href="https://www.jobleads.com/_nucf/svg-B6HgDs4Y.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin="" href="https://www.jobleads.com/_nucf/svg-DZ6_-8KJ.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin="" href="https://www.jobleads.com/_nucf/svg-Bqe82O70.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin="" href="https://www.jobleads.com/_nucf/svg-CxgdqPe7.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin="" href="https://www.jobleads.com/_nucf/svg-BXKL-lQK.f1777696.js" />
        <link rel="stylesheet" href="/nuxt/css/fonts-aurora.css" />
        <link rel="preload" href="/nuxt/fonts/inter-regular.woff2" as="font" type="font/woff2" crossOrigin="anonymous" />
        <link rel="preload" href="/nuxt/fonts/inter-medium.woff2" as="font" type="font/woff2" crossOrigin="anonymous" />
        <link rel="preload" href="/nuxt/fonts/right-grotesk-medium.otf" as="font" type="font/otf" crossOrigin="anonymous" />
        <script src="https://cdn.cookielaw.org/scripttemplates/202505.1.0/otBannerSdk.js"
          type="text/javascript"></script>
        <script src="https://static.hotjar.com/c/hotjar-2373682.js?sv=6"></script>
        <script src="//embed.typeform.com/next/embed.js"></script>
        <link rel="stylesheet" href="//embed.typeform.com/next/css/sidetab.css" />
        <link rel="modulepreload" as="script" crossOrigin=""
          href="https://www.jobleads.com/_nucf/ResumeBuilderEditorFormSecondary.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin=""
          href="https://www.jobleads.com/_nucf/UIColorPicker.vue.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin=""
          href="https://www.jobleads.com/_nucf/ResumeBuilderFormStyling.f1777696.js" />
        <link rel="stylesheet" crossOrigin="" href="https://www.jobleads.com/_nucf/ResumeBuilderFormStyling.f1777696.css" />
        <script src="https://script.hotjar.com/modules.ce37dfc81afa6fcb9f03.js"></script>
        <script src="https://bat.bing.com/p/action/26347591.js" type="text/javascript"
          data-ueto="ueto_1cfb6a7847"></script>
        <link rel="modulepreload" as="script" crossOrigin="" href="https://www.jobleads.com/_nucf/svg-_StXbozD.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin="" href="https://www.jobleads.com/_nucf/GoogleOneTap.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin="" href="https://www.jobleads.com/_nucf/index.f17776962.js" />
        <link rel="modulepreload" as="script" crossOrigin=""
          href="https://www.jobleads.com/_nucf/NewPlaceholder.f1777696.js" />
        <link rel="stylesheet" crossOrigin="" href="https://www.jobleads.com/_nucf/NewPlaceholder.f1777696.css" />
        <link rel="modulepreload" as="script" crossOrigin="" href="https://www.jobleads.com/_nucf/Placeholder.f1777696.js" />
        <link rel="stylesheet" crossOrigin="" href="https://www.jobleads.com/_nucf/Placeholder.f1777696.css" />
        <link rel="modulepreload" as="script" crossOrigin="" href="https://www.jobleads.com/_nucf/MainDetails.f1777696.js" />
        <link rel="stylesheet" crossOrigin="" href="https://www.jobleads.com/_nucf/MainDetails.f1777696.css" />
        <link rel="modulepreload" as="script" crossOrigin=""
          href="https://www.jobleads.com/_nucf/HeadhunterMatchesCard.f1777696.js" />
        <link rel="stylesheet" crossOrigin="" href="https://www.jobleads.com/_nucf/HeadhunterMatchesCard.f1777696.css" />
        <link rel="modulepreload" as="script" crossOrigin=""
          href="https://www.jobleads.com/_nucf/useHeadhunterMatchesTracking.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin="" href="https://www.jobleads.com/_nucf/Swiper.f1777696.js" />
        <link rel="stylesheet" crossOrigin="" href="https://www.jobleads.com/_nucf/Swiper.f1777696.css" />
        <link rel="modulepreload" as="script" crossOrigin=""
          href="https://www.jobleads.com/_nucf/jobLastSearchStore.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin="" href="https://www.jobleads.com/_nucf/Menu.f1777696.js" />
        <link rel="stylesheet" crossOrigin="" href="https://www.jobleads.com/_nucf/Menu.f1777696.css" />
        <link rel="modulepreload" as="script" crossOrigin="" href="https://www.jobleads.com/_nucf/Input.scss.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin=""
          href="https://www.jobleads.com/_nucf/prefixDataTestid.f1777696.js" />
        <link rel="stylesheet" crossOrigin="" href="https://www.jobleads.com/_nucf/Input.f1777696.css" />
        <link rel="modulepreload" as="script" crossOrigin="" href="https://www.jobleads.com/_nucf/UISelect.vue.f1777696.js" />
        <link rel="stylesheet" crossOrigin="" href="https://www.jobleads.com/_nucf/UISelect.f1777696.css" />
        <link rel="modulepreload" as="script" crossOrigin=""
          href="https://www.jobleads.com/_nucf/jobSavedSearchStore.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin=""
          href="https://www.jobleads.com/_nucf/LightCarousel.f1777696.js" />
        <link rel="stylesheet" crossOrigin="" href="https://www.jobleads.com/_nucf/LightCarousel.f1777696.css" />
        <link rel="stylesheet" crossOrigin="" href="https://www.jobleads.com/_nucf/index.f1777696.css" />
        <link rel="modulepreload" as="script" crossOrigin="" href="https://www.jobleads.com/_nucf/jobs.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin=""
          href="https://www.jobleads.com/_nucf/useJobsMobileNavigation.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin="" href="https://www.jobleads.com/_nucf/useIsMobile.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin=""
          href="https://www.jobleads.com/_nucf/vdbJobSavedSearchStore.f1777696.js" />
        <link rel="stylesheet" crossOrigin="" href="https://www.jobleads.com/_nucf/jobs.f1777696.css" />
        <link rel="modulepreload" as="script" crossOrigin="" href="https://www.jobleads.com/_nucf/index.f177769615.js" />
        <link rel="modulepreload" as="script" crossOrigin=""
          href="https://www.jobleads.com/_nucf/headhunterMatchStore.f1777696.js" />
        <link rel="stylesheet" crossOrigin="" href="https://www.jobleads.com/_nucf/headhunterMatchStore.f1777696.css" />
        <link rel="stylesheet" crossOrigin="" href="https://www.jobleads.com/_nucf/index.f177769612.css" />
        <link rel="modulepreload" as="script" crossOrigin="" href="https://www.jobleads.com/_nucf/search-jobs.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin="" href="https://www.jobleads.com/_nucf/site-notice.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin="" href="https://www.jobleads.com/_nucf/useMetaSeo.f1777696.js" />
        <link rel="stylesheet" crossOrigin="" href="https://www.jobleads.com/_nucf/site-notice.f1777696.css" />
        <link rel="modulepreload" as="script" crossOrigin="" href="https://www.jobleads.com/_nucf/report.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin=""
          href="https://www.jobleads.com/_nucf/useFreeResumeReviewPage.f1777696.js" />
        <link rel="stylesheet" crossOrigin="" href="https://www.jobleads.com/_nucf/report.f1777696.css" />
        <link rel="modulepreload" as="script" crossOrigin="" href="https://www.jobleads.com/_nucf/index.f177769616.js" />
        <link rel="stylesheet" crossOrigin="" href="https://www.jobleads.com/_nucf/index.f177769613.css" />
        <link rel="modulepreload" as="script" crossOrigin="" href="https://www.jobleads.com/_nucf/index.f177769611.js" />
        <link rel="stylesheet" crossOrigin="" href="https://www.jobleads.com/_nucf/index.f17776969.css" />
        <link rel="modulepreload" as="script" crossOrigin=""
          href="https://www.jobleads.com/_nucf/privacy-policy.f1777696.js" />
        <link rel="modulepreload" as="script" crossOrigin=""
          href="https://www.jobleads.com/_nucf/TermsPlaceholder.f1777696.js" />
        <link rel="stylesheet" crossOrigin="" href="https://www.jobleads.com/_nucf/TermsPlaceholder.f1777696.css" />
        <link rel="stylesheet" crossOrigin="" href="https://www.jobleads.com/_nucf/privacy-policy.f1777696.css" />
        <link rel="modulepreload" as="script" crossOrigin="" href="https://www.jobleads.com/_nucf/terms-of-use.f1777696.js" />
        <link rel="stylesheet" crossOrigin="" href="https://www.jobleads.com/_nucf/terms-of-use.f1777696.css"></link>
      </head> */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
